scada:
  ip: "10.0.0.10"
  port: 5020

plcs:
  - id: "PLC_PUMP_1"
    element_id: "PUMP1"
    ip: "10.0.0.1"


  - id: "PLC_PUMP_2"
    element_id: "PUMP2"
    ip: "10.0.0.11"

  - id: "PLC_TANK_1"
    element_id: "TANK"
    ip: "10.0.0.3"