simulation:
  mode: "closed_loop"   # closed_loop or open_loop
  duration_hours: 24
  step_minutes: 15
  start_clock_time: "00:00"

network:
  use_minicps: false
  link_delay_ms: 5
  link_bandwidth_mbps: 10
  loss_rate: 0.0
